[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"

[env]
SUPABASE_URL = { $ref = "SUPABASE_URL" }
SUPABASE_SERVICE_KEY = { $ref = "SUPABASE_SERVICE_KEY" }
RAILWAY_PORT = { $ref = "PORT" }